---
external_address: "{{ external_host_address }}"
external_interface: "{{ external_host_interface }}"
external_gateway: "{{ external_gateway_address }}"
internal_interface: "{{ internal_host_interface }}"
