---
- name: Networking | OpenVSwitch | Build Bridges (external,internal,ocp-mini-stack)
  openvswitch_bridge:
    bridge: external
    state: present
- openvswitch_bridge:
    bridge: internal
    state: present
- openvswitch_bridge:
    bridge: ocp-mini-stack
    state: present
#- openvswitch_port:
#    bridge: external
#    state: present
#    port: "{{ external_host_interface }}"
#- openvswitch_port:
#    bridge: external
#    state: present
#    port: "{{ internal_host_interface }}"
