---
# Install Snapd based LXD
- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int <= 31
- include: snap.yml
  when: ansible_facts['distribution'] != 'RedHat'
- include: configure.yml
  when: ansible_facts['distribution'] != 'RedHat'
